services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: uv run fastapi run app/main.py --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      maildev:
        condition: service_started
    environment:
      DATABASE_URL: postgresql://user:password@db/dbname
      SMTP_SERVER: maildev
      SMTP_PORT: 1025
      TZ: Europe/Paris

  db:
    image: postgres:18
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
      TZ: Europe/Paris
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d dbname"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"

  maildev:
    image: maildev/maildev:2.1.0
    ports:
      - "1080:1080"  # Web interface
      - "1025:1025"  # SMTP Server
    environment:
      - TZ=Europe/Paris

volumes:
  postgres_data:
