[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "dailymotion-user-auth"
requires-python = ">= 3.12"
version = "2026.3.18"
authors = [
  { name="Zackary Beaugelin", email="zackary@zbgn.fr" },
]
dependencies = [
  "asyncpg==0.31.0",
  "colorlog==6.10.1",
  "fastapi[standard]==0.135.1",
  "python-dotenv==1.2.2",
  "pytz==2026.1.post1",
]

[dependency-groups]
test = [
  "httpx==0.28.1",
  "psycopg[binary,pool]==3.3.3",
  "pytest>=9.0.2",
  "pytest-asyncio==1.4.0",
]
dev = [
  "ruff==0.15.6",
  "ty>=0.0.1",
]

[project.urls]
Homepage = "https://github.com/zbgn/dailymotion-user-auth"
Issues = "https://github.com/zbgn/dailymotion-user-auth/issues"

[tool.ruff]
# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

line-length = 120
indent-width = 4
target-version = "py312"

[tool.ruff.lint]
select = ["ALL"]
ignore = ["COM812", "ISC001", "D203", "D212"]

fixable = ["ALL"]
unfixable = []

dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.lint.per-file-ignores]
"**/test*/**.py" = [
  "S101",  # Use of assert detected
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"